angular.module('su.datepicker', [
  'su.datepicker.directives.suDatepickerDirectivesModule',
  'su.datepicker.filters.suDatepickerFiltersModule',
  'su.datepicker.templates.suDatepickerTemplatesModule' //generated by grunt-html2js
]);
